# Generated by cucumber-sinatra. (2014-09-12 09:33:29 +0100)

ENV['RACK_ENV'] = 'test'


require_relative '../../app/chitter.rb' 
require_relative '../../app/controllers/users.rb'
require_relative '../../app/controllers/sessions.rb'
require_relative '../../app/controllers/peeps.rb'
require_relative '../../app/controllers/website.rb'


require 'capybara'
require 'capybara/cucumber'
require 'rspec'



def test_app 
  Rack::Builder.new do
	map('/users') { run UsersController }
	map('/sessions') { run SessionsController }
	map('/peeps') { run PeepsController }
	map('/') { run WebsiteController }
  end
end




Capybara.app = test_app





class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitterWorld.new
end
